baseurl = https://px-study.netlify.app/
title = "Peixin 的杂七杂八"
author = "Peixin Nie"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Peixin 的杂七杂八"
  faviconfile = "images/logo.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "学习笔记"
    url = "/learningnotes"
    weight = 2
[[menu.primary]]
    name = "异想天开"
    url = "/think"
    title = "abcd"
    weight = 3
[[menu.primary]]
    name = "有意思"
    url = "/interesting/"
    weight = 4
[[menu.primary]]
    name = "关于我"
    url = "/aboutme/"
    weight = 5
